# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=80)),
                ('company_name', models.CharField(max_length=80)),
                ('job_title', models.CharField(max_length=80)),
                ('portal_url', models.CharField(max_length=80)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
