# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171128_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='portal_url',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
